language: python

python:
  - "3.5"
  - "3.6"

sudo: false

before_install:
  - pip install -r "requirements.txt"
  - pip install flake8
  - pip install coveralls
  - sudo apt-get install cloc
  - pip install bandit

install:
  - ./setup.py install

script:
  - flake8 .
  - cd tests
  - coverage run --source=graal run_tests.py

after_success:
  - coveralls
